@startuml farmearAura-DS-v2
title Farmear aura - Secuencia v2 (valoración del gesto)
participant ":Persona" as Persona
participant ":Gesto" as Gesto
participant ":Aura" as Aura
Persona -> Gesto : hacer()
activate Gesto
Gesto -> Gesto : valorar()
alt épico
  Gesto -> Aura : otorgar(+n)
else cringe
  Gesto -> Aura : restar(n)
end
Aura -> Persona : darAura(total)
deactivate Gesto
@enduml
